### ISSUE TITLE
2.0 -> 3.0 migration example isn't correct

### ISSUE THREAD

**Issue by pnomolos** [attr-encrypted/attr_encrypted#215]
This line:

```ruby
attr_encrypted :ssn, key: :encryption_key, v2_gcm_iv: :is_decrypting?(:ssn)
```

is invalid syntax.  As well, 

```ruby
def is_decrypting?(attribute)
  encrypted_atributes[attribute][operation] == :decrypting
end
```

misspells `encrypted_attributes` and references `operation` instead of `:operation`

I'd write a PR, but I'm not sure what to suggest.  As far as I can tell, the `attr_encrypted` options pass the instance to callable options, not the attribute being evaluated.

**Comment by rally25rs** [comment]
Curious why this is marked "closed".

```
attr_encrypted :ssn, key: :encryption_key, v2_gcm_iv: :is_decrypting?(:ssn)
```

still isn't valid syntax...

Related issue; `v2_gcm_iv` isn't documented as a valid option in the main options list either.

**Comment by saghaulor** [comment]
@rally25rs whoops I thought that I fixed the syntax error. It's simple enough to fix. Thanks for pointing it out.

I didn't document `v2_gcm_iv` in the main options list because I wanted to keep the documentation clean. That option is only relevant to a small group of users that made use of the v2 gem and are migrating to v3.

We have tried to make this gem a simple as possible to use. And yet people are still confused by it. So I've tried to write better documentation to improve usability. I don't want to muddy up that documentation with transient details. I felt it was better left documented in the relevant section.

**Comment by saghaulor** [comment]
Fixed here 6da4c55d6761611dd1deebe18825397f7ef1fa6f

**Comment by rally25rs** [comment]
@saghaulor Thanks for looking at that. It had crossed my mind to just remove that `:` but my thinking was that the `is_decrypting?` function would just get called once as the class was being defined and the resulting boolean value passed to `attr_encrypted`. I didn't see how `attr_encrypted` would know to call `is_decrypting?` every time it had to read or write the attribute.

**Comment by saghaulor** [comment]
@rally25rs it is a bit confusing, but the options are evaluated in the context of the instantiated object, not the class, as you alluded to, and as documented here https://github.com/attr-encrypted/attr_encrypted#options-are-evaluated

This allows you to make decisions during the different operations, for example, to switch which encryption key is used during decryption and encryption. Consequently, a path forward is provided for migrating from one implementation to another.

**Comment by rally25rs** [comment]
@saghaulor still not valid syntax

```
NoMethodError: undefined method `is_decrypting?' for UpgradeAttrEncrypted::User:Class
```

Tried adding a `self.` here:

```
    def self.is_decrypting?(attribute)
```

but that also didn't help.

**Comment by saghaulor** [comment]
@rally25rs `is_decrypting?(attribute)` is supposed to be an instance method, not a class method.

The syntax is valid. You didn't receive a syntax error, you received a undefined method error.

Did you include the method definition in your `UpgradeAttrEncrypted::User:Class` class?

**Comment by rally25rs** [comment]
@saghaulor Finally figured this out. 2 more errors;
1) you need `class User < ActiveRecord::Base` (at least my code did the way its set up)
2) `is_decrypting?` is indeed getting called just before `attr_encrypted` is called as I mentioned above.  But wrapping it in a Proc fixes that.

This is my working migration:

```
class UpgradeAttrEncrypted < ActiveRecord::Migration

  class User < ActiveRecord::Base
    attr_encrypted :ssn, key: secret_key, v2_gcm_iv: Proc.new {is_decrypting?(:ssn)}

    def self.is_decrypting?(attribute)
      encrypted_attributes[attribute][:operation] == :decrypting
    end
  end

  def change
    User.all.each do |user|
      old_ssn = user.ssn
      user.ssn = old_ssn
      user.save
    end
  end

end
```

**Comment by saghaulor** [comment]
@rally25rs I believe that the `:operation` option is only set at the instance level. As such, your `is_decrypting?` method should be an instance method. I believe you've hacked around it using a proc, but a safer and more correct way is to follow my instructions.

You're correct in that you need a class that inherits from ActiveRecord::Base.

**Comment by rally25rs** [comment]
@saghaulor sorry for all the back-and-forth...

I think this is what you are saying should work?

```
  class User < ActiveRecord::Base
    attr_encrypted :ssn, key: secret_key, v2_gcm_iv: is_decrypting?(:ssn)

    def is_decrypting?(attribute)
      encrypted_attributes[attribute][:operation] == :decrypting
    end
  end
```

that results in

```
NoMethodError: undefined method `is_decrypting?' for #<Class:0x007f87f3e91718>
```

-----

Ah, this actually seems to work though (taken from your "options are evaluated" link above which also shows a `proc` in an example)

```
  class User < ActiveRecord::Base
    attr_encrypted :ssn, key: secret_key, v2_gcm_iv: proc {|user| user.is_decrypting?(:ssn)}

    def is_decrypting?(attribute)
      encrypted_attributes[attribute][:operation] == :decrypting
    end
  end
```

☝️ I think this is probably what I want; a proper instance method, called wrapped in a proc 👍

**Comment by saghaulor** [comment]
It's odd that the example I provided doesn't work. I'm using that pattern in my code. I'm happy that you figured out an acceptable solution.
